import type { Challenge } from "./data";

export const extraChallengesByDiscipline: Record<string, Challenge[]> = {
  software: [
    {
      id: "software-hashmap-sessionization",
      title: "Sessionize Event Streams",
      prompt: "Given timestamped user events that can arrive slightly out of order, group them into sessions separated by 30 minutes of inactivity. Explain the algorithm, complexity, and tests you would write.",
      difficulty: "Foundation",
      signal: "Tests maps, sorting, interval reasoning, and test discipline.",
      starter: "Clarify whether events are grouped per user, how much disorder is allowed, and whether input can fit in memory before choosing the simplest correct approach.",
      confirms: "Common coding-screen themes include hash maps, sorting, interval grouping, and explicit edge-case testing.",
    },
    {
      id: "software-tree-permissions",
      title: "Hierarchical Permission Resolver",
      prompt: "Implement the reasoning for resolving inherited allow and deny rules in a resource tree where child nodes can override parent permissions and cycles must be rejected.",
      difficulty: "Core",
      signal: "Tests tree traversal, precedence rules, validation, and correctness reasoning.",
      starter: "Define permission precedence first, then choose the traversal and explain how you detect malformed or cyclic input.",
      confirms: "Tree traversal and rule-resolution problems are recurring interview patterns because they expose modeling and correctness skills.",
    },
    {
      id: "software-rate-limiter",
      title: "Distributed Rate Limiter",
      prompt: "Design a rate limiter for a public API that supports per-user and per-organization quotas across regions while remaining available during partial network failure.",
      difficulty: "Advanced",
      signal: "Tests distributed state, consistency tradeoffs, failure handling, and API design.",
      starter: "Start with the quota semantics and acceptable overage, then compare token bucket, fixed-window, and distributed coordination choices.",
      confirms: "Rate limiting is a standard systems-design topic because it combines algorithms, distributed coordination, and product tradeoffs.",
    },
    {
      id: "software-debug-memory-leak",
      title: "Production Memory Leak Investigation",
      prompt: "A stateless service slowly grows from 800 MB to 8 GB over several hours and is repeatedly OOM-killed. Walk through how you would isolate the cause before changing code.",
      difficulty: "Advanced",
      signal: "Tests production debugging, hypothesis sequencing, instrumentation, and communication.",
      starter: "Separate traffic-correlated growth, cache growth, retained objects, native memory, and dependency behavior before choosing tools or fixes.",
      confirms: "Senior software interviews increasingly include debugging and production reasoning in addition to algorithm work.",
    },
    {
      id: "software-concurrent-job-runner",
      title: "Concurrent Job Runner",
      prompt: "Design a worker that executes dependency-aware jobs with bounded concurrency, retries, cancellation, and exactly-once-visible completion semantics where possible.",
      difficulty: "Expert",
      signal: "Tests concurrency, queues, idempotency, failure semantics, and implementation tradeoffs.",
      starter: "Define job states and idempotency guarantees first, then explain scheduling, retry ownership, cancellation, and recovery after worker loss.",
      confirms: "Concurrency and job-processing design questions test the practical gap between correct local code and reliable production systems.",
    },
  ],
  data: [
    {
      id: "data-sql-window-analysis",
      title: "SQL Window Function Drill",
      prompt: "Write the logical SQL plan to identify each customer's longest streak of active weeks, rank customers within segment, and handle weeks with no events.",
      difficulty: "Foundation",
      signal: "Tests SQL window functions, date logic, grouping, and edge-case awareness.",
      starter: "Define the grain of the weekly table first, then use ordered windows to identify breaks before aggregating streaks.",
      confirms: "Window functions, cohort logic, and date handling remain common analytics and data-science interview topics.",
    },
    {
      id: "data-ab-test-guardrails",
      title: "A/B Test With Conflicting Metrics",
      prompt: "An experiment lifts conversion by 3% but worsens refund rate and support contacts. Decide whether to launch, what statistical checks matter, and what you would investigate next.",
      difficulty: "Core",
      signal: "Tests experiment interpretation, guardrail metrics, uncertainty, and decision quality.",
      starter: "Start with the experiment hypothesis, primary metric, guardrails, power, and whether the negative movements are practically and statistically meaningful.",
      confirms: "Experiment-analysis interviews commonly test whether candidates can move beyond p-values to product decisions and guardrails.",
    },
    {
      id: "data-causal-marketplace",
      title: "Marketplace Causal Inference",
      prompt: "A marketplace changes ranking logic in only some cities and gross bookings rise. Estimate the causal impact despite seasonality, spillovers, and non-random rollout order.",
      difficulty: "Advanced",
      signal: "Tests causal inference, quasi-experimental design, confounding, and marketplace reasoning.",
      starter: "Name why a naive before/after comparison is biased, then compare difference-in-differences, matching, synthetic controls, and sensitivity checks.",
      confirms: "Causal inference is a differentiating skill in senior data interviews where randomized experiments are not always available.",
    },
    {
      id: "data-ml-feature-store",
      title: "Feature Store Design Review",
      prompt: "Design the data and evaluation architecture for online and offline features used by a fraud model, with strict point-in-time correctness and low-latency serving.",
      difficulty: "Advanced",
      signal: "Tests ML systems, leakage prevention, freshness, reliability, and operational tradeoffs.",
      starter: "Start with training-serving consistency, event time versus processing time, and the latency and freshness requirements for each feature family.",
      confirms: "Modern ML interviews often test production data systems and evaluation integrity, not just model selection.",
    },
    {
      id: "data-llm-eval-calibration",
      title: "LLM Evaluator Calibration",
      prompt: "Human reviewers and an automated LLM judge disagree on 18% of assistant responses. Design a calibration study and decide whether the automated judge is safe to use for release gating.",
      difficulty: "Expert",
      signal: "Tests evaluator validity, sampling, disagreement analysis, measurement error, and launch judgment.",
      starter: "Define the decision the evaluator will support, then stratify disagreement cases, measure reviewer agreement, and set thresholds by failure severity rather than one aggregate score.",
      confirms: "AI evaluation roles increasingly require rigorous treatment of automated judges, human labels, and slice-level failure analysis.",
    },
  ],
  product: [
    {
      id: "product-estimation-capacity",
      title: "Product Estimation Under Uncertainty",
      prompt: "Estimate the first-year demand for a paid team collaboration feature with limited historical data, and explain which assumptions you would validate before investing heavily.",
      difficulty: "Foundation",
      signal: "Tests structured estimation, assumptions, segmentation, and business judgment.",
      starter: "Choose a top-down or bottom-up model, state the few assumptions that dominate the estimate, and show how you would validate them cheaply.",
      confirms: "Estimation questions remain useful for testing decomposition and comfort with ambiguity in PM interviews.",
    },
    {
      id: "product-metric-tree",
      title: "Metric Tree for Collaboration",
      prompt: "Build a metric tree for a collaborative workspace product and identify which metrics you would use to diagnose a sudden drop in weekly active teams.",
      difficulty: "Core",
      signal: "Tests north-star reasoning, metric decomposition, diagnostics, and prioritization.",
      starter: "Define the core value event first, then decompose acquisition, activation, engagement, retention, and quality without creating a vanity-metric tree.",
      confirms: "Metric design and diagnosis are common PM execution interview formats.",
    },
    {
      id: "product-failed-launch",
      title: "Recover a Failed Launch",
      prompt: "A highly promoted feature launches on time but adoption is weak and existing users complain that the workflow is harder. Decide what to do in the next two weeks.",
      difficulty: "Advanced",
      signal: "Tests post-launch diagnosis, prioritization, user empathy, and executive communication.",
      starter: "Separate discoverability, value, usability, and migration problems, then choose reversible actions and evidence that would justify larger changes.",
      confirms: "Senior PM interviews test how candidates respond when the launch itself does not validate the product thesis.",
    },
    {
      id: "product-platform-api",
      title: "API Platform Strategy",
      prompt: "A successful end-user product is considering a public API. Define the target customer, initial surface area, business model, developer experience, and platform risks.",
      difficulty: "Advanced",
      signal: "Tests platform product thinking, ecosystem strategy, sequencing, and developer empathy.",
      starter: "Start with the external job-to-be-done and why an API is the right product surface before discussing endpoints or pricing.",
      confirms: "Platform PM loops often probe ecosystem design, API strategy, incentives, and long-term operating costs.",
    },
    {
      id: "product-ai-memory",
      title: "AI Memory Product Decision",
      prompt: "Decide whether and how to launch persistent memory for an AI assistant where personalization value conflicts with privacy, user control, and the risk of incorrect remembered context.",
      difficulty: "Expert",
      signal: "Tests AI product judgment, trust, privacy, controls, metrics, and staged rollout design.",
      starter: "Define the user value and memory boundaries first, then design consent, inspection, correction, deletion, failure handling, and launch metrics.",
      confirms: "AI PM interviews increasingly test product value and safety as one integrated decision rather than separate checklists.",
    },
  ],
  design: [
    {
      id: "design-accessibility-checkout",
      title: "Accessible Checkout Redesign",
      prompt: "Redesign a checkout flow that performs well for most users but has major completion problems for keyboard, screen-reader, and low-vision users.",
      difficulty: "Foundation",
      signal: "Tests inclusive design, journey analysis, prioritization, and validation planning.",
      starter: "Map the critical path and failure points first, then explain interaction, semantics, focus order, error handling, and how you would test with users.",
      confirms: "Accessibility is increasingly expected as a core product-design competency rather than a post-design compliance step.",
    },
    {
      id: "design-critique-dashboard",
      title: "Dashboard Critique",
      prompt: "Critique an analytics dashboard that has strong visual polish but users miss important anomalies and struggle to decide what action to take next.",
      difficulty: "Core",
      signal: "Tests critique structure, hierarchy, information design, and action-oriented reasoning.",
      starter: "Start with user goals and decision moments, then critique hierarchy, density, comparison context, alerting, and action affordances.",
      confirms: "Design critique interviews evaluate whether candidates can connect visual choices to user comprehension and product outcomes.",
    },
    {
      id: "design-offline-mobile",
      title: "Offline-First Mobile Workflow",
      prompt: "Design a field-service workflow for users who frequently lose connectivity but must capture work, resolve conflicts, and know what has safely synchronized.",
      difficulty: "Advanced",
      signal: "Tests state modeling, failure UX, trust, mobile constraints, and systems thinking.",
      starter: "Define what must work offline, which conflicts are possible, and how status, retries, and reconciliation should be communicated without overwhelming the user.",
      confirms: "Senior design exercises often probe difficult system states rather than only happy-path screen composition.",
    },
    {
      id: "design-enterprise-permissions",
      title: "Enterprise Permission Experience",
      prompt: "Design the permission-management experience for a multi-team enterprise workspace with inherited roles, exceptions, external guests, and audit requirements.",
      difficulty: "Advanced",
      signal: "Tests complex information architecture, mental models, safety, and progressive disclosure.",
      starter: "Start with the administrator's mental model and common tasks, then surface inheritance, exceptions, risky changes, and auditability clearly.",
      confirms: "Enterprise design interviews test whether candidates can make complex policy and state understandable without hiding important consequences.",
    },
    {
      id: "design-ai-agent-control",
      title: "Human Control for AI Agents",
      prompt: "Design the interaction model for an AI agent that can execute multi-step tasks, spend money within limits, and ask for approval when confidence or risk crosses a threshold.",
      difficulty: "Expert",
      signal: "Tests human-in-the-loop design, trust calibration, permissions, reversibility, and failure-state UX.",
      starter: "Define action classes by reversibility and risk, then design previews, approvals, progress visibility, interruption, recovery, and audit history.",
      confirms: "AI interaction design increasingly centers on delegation boundaries and user control over consequential actions.",
    },
  ],
  devops: [
    {
      id: "devops-linux-saturation",
      title: "Linux Host Saturation Triage",
      prompt: "A Linux service host shows high load average, moderate CPU utilization, rising request latency, and no obvious application errors. Walk through the investigation from the kernel outward.",
      difficulty: "Core",
      signal: "Tests Linux fundamentals, CPU versus I/O reasoning, process inspection, and disciplined troubleshooting.",
      starter: "Start by distinguishing runnable tasks from blocked tasks, then inspect CPU, memory pressure, disk and network I/O, process state, and recent change history.",
      confirms: "Practical Linux troubleshooting remains common in SRE and infrastructure interviews.",
    },
    {
      id: "devops-dns-tls-outage",
      title: "DNS and TLS Failure Chain",
      prompt: "Users in one region report intermittent connection failures after a certificate rotation and DNS change. Diagnose the issue across resolver, routing, load balancer, TLS, and application layers.",
      difficulty: "Advanced",
      signal: "Tests networking fundamentals, layered diagnosis, certificate operations, and blast-radius reasoning.",
      starter: "Separate name resolution, reachability, TCP establishment, TLS negotiation, and HTTP behavior, and compare healthy versus failing regions at each layer.",
      confirms: "Networking and TLS troubleshooting are recurring differentiators in senior SRE interviews.",
    },
    {
      id: "devops-kubernetes-evictions",
      title: "Kubernetes Eviction Storm",
      prompt: "A Kubernetes cluster begins evicting pods during peak traffic while node CPU looks healthy. Stabilize the service and determine whether requests, limits, memory pressure, storage, or scheduling is responsible.",
      difficulty: "Advanced",
      signal: "Tests Kubernetes scheduling, resource management, observability, and incident response.",
      starter: "Start with user impact and eviction reasons, then inspect node conditions, requests and limits, working sets, ephemeral storage, autoscaling, and recent deployments.",
      confirms: "Kubernetes resource and scheduling problems are standard platform-engineering interview material.",
    },
  ],
  security: [
    {
      id: "security-web-auth-bypass",
      title: "Web Authorization Bypass Review",
      prompt: "A multi-tenant API verifies authentication correctly but a bug report suggests users can access objects owned by other tenants by changing an identifier. Investigate and redesign the control model.",
      difficulty: "Foundation",
      signal: "Tests authentication versus authorization, object-level access control, testing, and remediation thinking.",
      starter: "Confirm the trust boundary and object ownership model, then trace where authorization is enforced and how you would prevent scattered checks from drifting.",
      confirms: "Broken object-level authorization is a common application-security scenario and a strong test of basic control reasoning.",
    },
    {
      id: "security-cloud-iam",
      title: "Cloud IAM Blast Radius",
      prompt: "A production cloud account has hundreds of roles, broad wildcard permissions, CI identities, and human break-glass access. Design a path to least privilege without breaking operations.",
      difficulty: "Core",
      signal: "Tests IAM modeling, migration strategy, telemetry, privilege reduction, and operational safety.",
      starter: "Inventory identities and actual permission use first, then prioritize high-risk privileges, staged policy tightening, break-glass controls, and detection.",
      confirms: "Cloud security interviews commonly test practical IAM hardening rather than idealized greenfield policy design.",
    },
    {
      id: "security-detection-exfiltration",
      title: "Data Exfiltration Detection",
      prompt: "Design detections for a legitimate employee account that begins downloading unusual volumes of sensitive data while staying within normal authentication patterns.",
      difficulty: "Advanced",
      signal: "Tests behavioral detection, telemetry, baselining, false positives, and response planning.",
      starter: "Define useful data-access signals and peer baselines, then combine volume, sensitivity, novelty, destination, and temporal patterns before choosing response automation.",
      confirms: "Detection-engineering interviews test signal quality and operational response, not just attack taxonomy.",
    },
    {
      id: "security-supply-chain",
      title: "Software Supply Chain Compromise",
      prompt: "A popular internal dependency may have been compromised upstream. Decide how you would establish exposure, contain risk, preserve evidence, and prevent recurrence across hundreds of services.",
      difficulty: "Advanced",
      signal: "Tests incident scope, dependency inventory, artifact trust, containment, and organizational coordination.",
      starter: "Establish affected versions and build provenance first, then identify where artifacts ran, isolate sensitive workloads, and preserve evidence before broad remediation.",
      confirms: "Supply-chain incidents expose whether senior candidates can coordinate technical containment at organizational scale.",
    },
    {
      id: "security-ai-model-exfiltration",
      title: "AI Data Exfiltration Defense",
      prompt: "An AI assistant can search internal documents and call SaaS tools. Design controls that reduce the chance an attacker can use prompt injection or tool chaining to exfiltrate confidential data.",
      difficulty: "Expert",
      signal: "Tests capability security, authorization, data boundaries, prompt-injection resilience, and monitoring.",
      starter: "Treat model output as untrusted, minimize tool authority, enforce policy outside the model, and define explicit data-flow and approval boundaries before adding detection layers.",
      confirms: "AI security interviews increasingly distinguish model instructions from enforceable authorization and capability controls.",
    },
  ],
  qa: [
    {
      id: "qa-api-contract",
      title: "API Contract Regression",
      prompt: "A backend team is changing a widely used API while mobile clients may remain on old versions for months. Design the compatibility and regression strategy.",
      difficulty: "Foundation",
      signal: "Tests contract testing, compatibility, versioning, and risk-based coverage.",
      starter: "List consumers and compatibility guarantees first, then cover schema changes, behavior changes, test data, monitoring, and rollback.",
      confirms: "API compatibility is a common QA and SDET interview scenario because failures often span teams and release cadences.",
    },
    {
      id: "qa-performance-degradation",
      title: "Performance Regression Gate",
      prompt: "A release passes functional tests but p95 latency is 18% worse under production-like load. Decide whether to block, investigate, or launch with monitoring.",
      difficulty: "Core",
      signal: "Tests performance testing, baselines, variance, user impact, and release judgment.",
      starter: "Validate the benchmark and variance first, then connect the regression to SLOs, capacity headroom, user impact, and reversibility.",
      confirms: "Performance and reliability quality gates are common in senior test-engineering interviews.",
    },
    {
      id: "qa-data-pipeline-quality",
      title: "Data Pipeline Quality Strategy",
      prompt: "Design the test strategy for a batch and streaming pipeline where late events, duplicates, schema evolution, and backfills can silently corrupt business metrics.",
      difficulty: "Advanced",
      signal: "Tests data-quality validation, invariants, observability, and layered automation.",
      starter: "Define invariants at ingestion, transformation, and serving layers, then cover replay, idempotency, schema contracts, reconciliation, and anomaly detection.",
      confirms: "Modern QA roles increasingly cover data systems where correctness cannot be reduced to UI assertions.",
    },
    {
      id: "qa-mobile-chaos",
      title: "Mobile Reliability Test Matrix",
      prompt: "Build a release test matrix for a mobile app that must survive flaky networks, backgrounding, OS upgrades, low storage, retries, and partially completed transactions.",
      difficulty: "Expert",
      signal: "Tests stateful mobile testing, failure injection, risk prioritization, and automation strategy.",
      starter: "Prioritize irreversible and money- or data-affecting flows, then test state transitions across network loss, process death, retries, storage pressure, and version changes.",
      confirms: "Senior mobile QA interviews test resilience across device and lifecycle states, not only nominal feature coverage.",
    },
  ],
};
